name: tox

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: rm -f /etc/boto.cfg
    - run: pip3 install --upgrade pip setuptools
    - run: pip3 install 'tox'
    - run: tox -- -n0

    - name: Run coverage
      if: matrix.python-version == '3.8'
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        fail_ci_if_error: false
